# Setup
title:		  Study Log
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       2narabbit
  url:        https://2narabbit.github.io

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
